### ISSUE TITLE
libcli missing

### ISSUE THREAD

**Issue by yverry** [juliogonzalez/winexe-rpm#1]
Hi,
I've tried to build package on centos6 but with error:

```
+ ./waf configure build
Setting top to                           : /tmp/another/winexe-rpm/BUILD/winexe-1.1/source
Setting out to                           : /tmp/another/winexe-rpm/BUILD/winexe-1.1/source/build
Checking for 'gcc' (c compiler)          : /usr/bin/gcc
Checking for program pkg-config          : /usr/bin/pkg-config
Checking for 'dcerpc'                    : yes
Checking for 'talloc'                    : yes
SAMBA_INCS set to                        : /usr/include/samba-4.0
SAMBA_LIBS set to                        : []
Checking for samba_util.h                : yes
Checking for core/error.h                : yes
Checking for credentials.h               : yes
Checking for dcerpc.h                    : yes
Checking for gen_ndr/ndr_svcctl_c.h      : yes
Checking for popt.h                      : yes
Checking for smb_cli.h                   : yes
Checking for smb_cliraw.h                : yes
Checking for smb_composite.h             : yes
Checking for tevent.h                    : yes
Checking for util/debug.h                : yes
```

and specially:

```
Checking for library cli-ldap            : not found
Checking for library :libcli-ldap.so.0   : not found
Build of shared winexe                   : disabled
Cannot continue! Please either install Samba shared libraries and re-run waf, or download the Samba source code and re-run waf with the "--samba-dir" option.
(complete log in /tmp/another/winexe-rpm/BUILD/winexe-1.1/source/build/config.log)
```

cli-ldap and lib missing because name is incorrect.
The easiest way to solve this issue is to create symlink like that:

```
cd /usr/lib64/samba/
ln -s libcli-ldap-samba4.so libcli-ldap.so.0
ln -s libdcerpc-samba4.so libdcerpc-samba.so.0
ln -s liberrors-samba4.so liberrors.so.0
```

I think `winexe-rpm`script can create symlink ?

Regards,

**Comment by juliogonzalez** [comment]
Hi @yanntech.

Thanks for the report. 

I was making some checks and it seems this is a change that happened with Samba 4.2.

For Samba 4.0:

```
[root@f0881b36f690 ~]# rpm2cpio samba4-libs-4.0.0-66.el6_6.rc4.x86_64.rpm | cpio -idmv &> /dev/null && ll usr/lib64/samba/libcli-ldap*
-rwxr-xr-x. 1 root root 24936 Feb 23  2015 usr/lib64/samba/libcli-ldap-common.so
-rwxr-xr-x. 1 root root 67528 Feb 23  2015 usr/lib64/samba/libcli-ldap.so
```

For Samba 4.2:

```
[root@f0881b36f690 ~]# rpm2cpio samba4-libs-4.2.10-6.el6_7.x86_64.rpm | cpio -idmv &> /dev/null && ll usr/lib64/samba/libcli-ldap*
-rwxr-xr-x. 1 root root 30616 Apr 12 22:35 usr/lib64/samba/libcli-ldap-common-samba4.so
-rwxr-xr-x. 1 root root 75752 Apr 12 22:35 usr/lib64/samba/libcli-ldap-samba4.so
```

Creating those links without consulting the user is a bad idea (as it's changing the content deployed by one of the system packages).

I'll change the script to check for the libraries, if libraries are not found, the script will exit with a controlled error and will offer to run the script with a parameter to fix the problem. And of course I'll document this at the README file.

**Comment by juliogonzalez** [comment]
Or, in fact, it would be better to patch winexe so it can work with samba4 >= 4.2 library changes, as nobody should be using CentOS6 with Samba 4.0 anymore (among other things, because of the [badlock bug](http://badlock.org/).

I'll try to fix the problem using this solution.

**Comment by juliogonzalez** [comment]
@yanntech, I uploaded a commit to a [separate branch samba42](https://github.com/juliogonzalez/winexe-rpm/tree/samba42).

So far I'm able to compile and run a remote powershell script, and an interactive CMD from CentOS6.7 and CentOS7.2 (remote instance was Windows 7).

The good thing is that with this patch, there's no need to create any symlinks.

Also we recover CentOS7 support (it was [broken since CentOS decided to move debugging functions to private library which is not accesible to winexe](https://bugzilla.samba.org/show_bug.cgi?id=10962)). The bad part of course is that users will loose the DEBUG messages, but I don't have enough time and C knowledge to fix this.

If everything is OK tomorrow after I run some more tests, I'll merge the changes into master and then I'll promote a new release.

**Comment by juliogonzalez** [comment]
@yanntech, I finally fixed CentOS6 support: there's a new commit at master branch, and a new release 1.1-1b787d2.1.

I'll issue a release 1.1-1b787d2.2 soon, with CentOS7 working again. I want to see if I'm able to change the DEBUG messages to simple stdout messages. If not, I'll just apply the patch I already have.

Closing a solved. Please let me know if you have more feedback.
